# Generated by Django 4.0 on 2023-08-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacesApi', '0002_remove_file_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECU_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('com_type', models.CharField(blank=True, max_length=200, null=True)),
                ('repro_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('req_ecu_id', models.CharField(blank=True, max_length=200, null=True)),
                ('res_ecu_id', models.CharField(blank=True, max_length=200, null=True)),
                ('trigger_msg_id', models.CharField(blank=True, max_length=200, null=True)),
                ('alive_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('did_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(max_length=30, null=True)),
                ('message_content', models.CharField(max_length=200, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
